apiVersion: v1
kind: Service
metadata:
  name: service-flask-app
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: 30000
  selector:
    app: flask-app